using System.Collections.Generic;
using UnityEngine;

public static class FightersTestData
{

    // Player values and skills
    // VALUES FOR TESTING. DICTIONARY IS OVERRIDDEN IF SAVEFILE EXISTS
    public static Dictionary<string, int> playerFighterStats =
    new Dictionary<string, int>
    {
        {"lv", 1},
        {"xp", 0},
        {"hitPoints", 20},
        {"strength", 3},
        {"agility", 20},
        {"speed", 20},
        {"counterRate", 0},
        {"reversalRate", 0},
        {"armor", 0},
        {"criticalRate", 0},
        {"sabotageRate", 0},
    };

    public static List<string> playerFighterSkills = new List<string> {
        Skills.SkillsList.SIXTH_SENSE.ToString(),
        Skills.SkillsList.HOSTILITY.ToString(),
        Skills.SkillsList.TOUGHENED_SKIN.ToString(),
        Skills.SkillsList.ARMOR.ToString(),
        Skills.SkillsList.CRITICAL_STRIKE.ToString(),
        Skills.SkillsList.SABOTAGE.ToString(),
    };

    // CPU values
    // FIXME: These should be calculated/randomized depending on the players level
    // VALUES FOR TESTING. DICTIONARY WILL BE OVERRIDDEN WHEN AUTOGENERATED CPU IS ADDED
    public static Dictionary<string, int> cpuFighterStats =
    new Dictionary<string, int>
    {
        {"lv", 1},
        {"xp", 0},
        {"hitPoints", 20},
        {"strength", 3},
        {"agility", 20},
        {"speed", 20},
        {"counterRate", 0},
        {"reversalRate", 0},
        {"armor", 0},
        {"criticalRate", 0},
        {"sabotageRate", 0},
    };

    public static List<string> cpuFighterSkills = new List<string> {
        Skills.SkillsList.SIXTH_SENSE.ToString(),
        Skills.SkillsList.HOSTILITY.ToString(),
        Skills.SkillsList.TOUGHENED_SKIN.ToString(),
        Skills.SkillsList.ARMOR.ToString(),
        Skills.SkillsList.CRITICAL_STRIKE.ToString(),
        Skills.SkillsList.SABOTAGE.ToString(),
    };

    public static string cpuFighterName = "Smasher";
}
