using UnityEngine;

public static class RandomNamesGenerator
{
    public static string[] nicknames =
    {
    "Nega Drive",
    "Yellow Corset",
    "Bad Arcade",
    "Eat Grass",
    "Plumber Luigi",
    "Tou Nugrau",
    "Hot Laptop",
    "Dezy Binder",
    "Ultra Mario",
    "Kimba Millica",
    "Mongo Boggie",
    "Hampus Mosh",
    "Big Glock",
    "Jungle Junk",
    "Little Cleber",
    "Naun Seynada",
    "Ruim Casual",
    "Sister of iNocente",
    "Magician Molixo",
    "Naglic Batata",
    "Idyota do Feedback",
    "Brain Damage",
    "Mickey Gangster",
    "Keima Clothing",
    "Fortis Naite",
    "Professor Terranova",
    "NemCheira",
    "lieved belts",
    "ZereiPornhub",
    "Roger feder",
    "Detoxa Ralph",
    "Captain Funeral",
    "Magnetic Satan",
    "Hema Toma",
    "AkitemProbrema",
    "Lady Doom",
    "Look boy",
    "Kano Furado",
    "TeinetêDuplo",
    "Boisonaru",
    "Eighteen",
    "RoyceGracinha",
    "SpiderCão",
    "MashaeaUrsa",
    "TirodeMeta",
    "LargaMina",
    "Conan Osiris",
    "Gangsta da Roça",
    "Nick Bosta",
    "Molek Asno",
    "Go horse",
    "Eu_Sou Molixo",
    "Anarch",
    "Your Terror",
    "Sandokano",
    "Enxomill",
    "Castle Owner",
    "MestreMete",
    "Narutom",
    "Sadistic Husaine",
    "Emperor of Acre",
    "They Invoca",
    "Cabrada Plague",
    "MarcadopaDying",
    "Jone Snou",
    "Salt Azar",
    "Tyrone Martelo",
    "MeioCroft",
    "MCBinLaiden",
    "Gokugeta",
    "Burnt out",
    "Telecommunication",
    "HackerHappy",
    "Emao Dimais",
    "Fail Error",
    "Luminous Apache",
    "Chinooka",
    "Tomahank",
    "Moiseucano",
    "Madrugueiro",
    "TronquinhoDisney",
    "JoniJones",
    "McNabo",
    "Eros Ramalhotti",
    "Wild Macaroni",
    "Silvestre Estaladone",
    "Arnaldão Sueternegro",
    "From Andaime",
    "Chuquenoris",
    "Error 500",
    "Raphael",
    "Donatelador",
    "Leo Nardo",
    "Mike inBrazil",
    "Bunker Smash",
    "DitongoNasal",
    "Odeyo Anime",
    "Esteven Sigal",
    "North Fort",
    "Golvig",
    "Igninitis",
    "Ioguss",
    "Jayldrog",
    "Kalodor",
    "Kalseru",
    "Kolzreid",
    "Lavatius",
    "Malumka",
    "Mortusra",
    "Nemredilth",
    "Nightwing",
    "Pondra",
    "Sakakara",
    "Sanguisus",
    "Serpretus",
    "Shadoras",
    "Shirmyl",
    "Skeltos",
    "Tendris",
    "Turvass",
    "Vayzen",
    "Ytanonth",
    "Zapptos",
    "Zynthasiu",
    "Miley Dryus",
    "Fizz Khalifa",
    "Bilbo Swaggins",
    "HanSoloQ",
    "Carry Potter",
    "Jim Carry",
    "Bruce Vayne",
    "Darth Veigar",
    "Brand Pitt",
    "Morgana Freeman",
    "HowIMetYourMundo",
    "DeadChixDontSayNo",
    "2fat2carry",
    "CaitUltedJFK",
    "HakunaMatata",
    "BongHit420",
    "AFKennedy",
    "AlmostEvil665",
    "Fizz In My Pants",
    "Adolf Critler",
    "Kraken",
    "Bender",
    "Lynch",
    "Big Papa",
    "Mad Dog",
    "Bowser",
    "Bruise",
    "Psycho",
    "Cannon",
    "Ranger",
    "Clink",
    "Ratchet",
    "Cobra",
    "Reaper",
    "Colt",
    "Rigs",
    "Crank",
    "Ripley",
    "Creep",
    "Roadkill",
    "Daemon",
    "Ronin",
    "Decay",
    "Rubble",
    "Diablo",
    "Sasquatch",
    "Doom",
    "Scar",
    "Dracula",
    "Shiver",
    "Dragon",
    "Skinner",
    "Fender",
    "Skull Crusher",
    "Fester",
    "Slasher",
    "Fisheye",
    "Steelshot",
    "Flack",
    "Surge",
    "Gargoyle",
    "Sythe",
    "Grave",
    "Trip",
    "Gunner",
    "Trooper",
    "Hash",
    "Tweek",
    "Hashtag",
    "Vein",
    "Indominus",
    "Void",
    "Ironclad",
    "Wardon",
    "Killer",
    "Wraith",
    "Knuckles",
    "Zero",
    "Steel",
    "Kevlar",
    "Lightning",
    "Tito",
    "Bullet-Proof",
    "Fire-Bred",
    "Titanium",
    "Hurricane",
    "Ironsides",
    "Iron-Cut",
    "Tempest",
    "Iron Heart",
    "Steel Forge",
    "Pursuit",
    "Steel Foil",
    "Sick Rebellious Names",
    "Upsurge",
    "Uprising",
    "Overthrow",
    "Breaker",
    "Sabotage",
    "Dissent",
    "Subversion",
    "Rebellion",
    "Insurgent",
    "Accidental Genius",
    "Acid Gosling",
    "Admiral Tot",
    "AgentHercules",
    "Airport Hobo",
    "Alley Frog",
    "Alpha",
    "AlphaReturns",
    "Angel",
    "AngelsCreed",
    "Arsenic Coo",
    "Atomic Blastoid",
    "Automatic Slicer",
    "Baby Brown",
    "Back Bett",
    "Bad Bunny",
    "Amazon",
    "Majesty",
    "Anomaly",
    "Malice",
    "Banshee",
    "Mannequin",
    "Belladonna",
    "Minx",
    "Beretta",
    "Mirage",
    "Black Beauty",
    "Nightmare",
    "Calypso",
    "Nova",
    "Carbon",
    "Pumps",
    "Cascade",
    "Raven",
    "Colada",
    "Resin",
    "Cosma",
    "Riveter",
    "Cougar",
    "Rogue",
    "Countess",
    "Roulette",
    "Enchantress",
    "Shadow",
    "Enigma",
    "Siren",
    "Femme Fatale",
    "Stiletto",
    "Firecracker",
    "Tattoo",
    "Geisha",
    "T-Back",
    "Goddess",
    "Temperance",
    "Half Pint",
    "Tequila",
    "Harlem",
    "Terror",
    "Heroin",
    "Thunderbird",
    "Infinity",
    "Ultra",
    "Insomnia",
    "Vanity",
    "Ivy",
    "Velvet",
    "Legacy",
    "Vixen",
    "Lithium",
    "Voodoo",
    "Lolita",
    "Wicked",
    "Lotus",
    "Widow",
    "Mademoiselle",
    "Xenon",
    "The Great Shark",
    "Black Dragon",
    "The Red Wolf",
    "Blue Whale",
    "The Green Tiger",
    "Yellow Lion",
    "The Purple Bear",
    "The Brown Fox",
    "Gray Cat",
    "The Orange Frog",
    "Pink dolphin",
    "Silver Eagle",
    "Golden Hawk",
    "Grey Owl",
    "The Dark Horse",
    "The Trooper",
    "My Steel Shot",
    "Creepy Bug",
    "Dragon Fire",
    "Graveyard",
    "Vein Arch",
    "Bowser Bee",
    "Decay Master",
    "Big Papa",
    "Scar Bearer",
    "Iron Clan",
    "Mad Dog",
    "Rubble",
    "The Warden",
    "Skinner",
    "Skinny Gamer",
    "Run Fast",
    "Meta Knight",
    "League of Legends",
    "Cherry",
    "Mario Brothers",
    "Ori Super",
    "Nidoking",
    "Link Man",
    "Evil Genius",
    "Wario",
    "Raptor",
    "Valgazza",
    "Madden NFL",
    "Super Smash Bros",
    "Feta",
    "Alice",
    "Alex Jones",
    "Waluigi",
    "Diablo",
    "Dweezil",
    "Mim",
    "Zelda",
    "Weim",
    "Junk",
    "Thermajin",
    "Terraria",
    "Advanced Gaming",
    "Uncharted",
    "Peach",
    "Superboy",
    "Donkey Kong",
    "Dragon",
    "Fallout",
    "Raging Ogres",
    "Powerdrive",
    "Candy Cane",
    "Magic",
    "Minecraft",
    "Umara",
    "Pinball Tables",
    "World of Warcraft",
    "Ninjas in Pajamas",
    "Lazir",
    "Lara Croft",
    "Nihnum",
    "Trax",
    "Rose",
    "Fizz",
    "Finger of Death",
    "Criss Cross",
    "Bug Blitz",
    "Mad Dog",
    "Ballistic",
    "Uprising",
    "Aero",
    "K-9",
    "Wildcat",
    "Blonde",
    "Electric Saturn",
    "Fire Fish",
    "Mortar",
    "Steelshot",
    "Vein",
    "Socket",
    "Arsenal",
    "Wolf",
    "Skinner",
    "Fast Draw",
    "Khan",
    "Creep",
    "Claw",
    "Bitmap",
    "Blistered Outlaw",
    "Rocky Highway",
    "Shadow Bishop",
    "DriftDetector",
    "Screw",
    "Black Mamba",
    "Rapid River",
    "Rotten Zucchini",
    "Sandwich Deliveries",
    "Sharks of Atlantis",
    "Apple Bob",
    "Clash of Cooks",
    "Crayon Crime",
    "Crazy Factory",
    "Bananas n Chips",
    "Cactus",
    "Call of Dowson",
    "Candy Crush",
    "Candy Land",
    "Danknado",
    "Dodge the Shoe",
    "Fortnite Couch",
    "Gardening Gophers",
    "Grand Theft Auto",
    "Grandma’s Nose",
    "Horse Herpes",
    "James Bomb",
    "Kingdom of Memes",
    "Mario Kart",
    "Meme Man",
    "Minecraft",
    "Minecraft",
    "Mustache Smack",
    "My Little Balloon",
    "Nesting Hens",
    "Nintendo",
    "Online Games",
    "Pacman",
    "Pinch the Pear",
    "Pokemon",
    "Pokemon",
    "Puds",
    "Skyrim",
    "Star Wars",
    "Super Mario",
    "Superior Succotash",
    "Outrageous Dominance",
    };

    public static string generateRandomName()
    {
        int randomIndexForNickNames = Random.Range(0, nicknames.Length);
        return nicknames[randomIndexForNickNames];
    }
};
